services:
  aas-env:
    image: eclipsebasyx/aas-environment:2.0.0-SNAPSHOT-273887a
    ports:
      - "8081:8081"
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      SPRING_DATA_MONGODB_HOST: mongo
      SPRING_DATA_MONGODB_DATABASE: basyx
      SPRING_DATA_MONGODB_PORT: 27017
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8081/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - basyx-net

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping').ok"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - basyx-net

networks:
  basyx-net:
