services:
  faaast:
    image: fraunhoferiosb/faaast-service:1.3.0
    ports:
      - "8080:443"
    volumes:
      - ./faaast-config.json:/app/resources/config.json
      - ./model.json:/app/resources/model.json
    environment:
      faaast_config: /app/resources/config.json
      faaast_model: /app/resources/model.json
    healthcheck:
      test: ["CMD-SHELL", "wget --no-check-certificate -qO- http://localhost:443/api/v3.0/shells || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 12
      start_period: 30s
